version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "bun*"
          - "koa"
          - "@koa/*"
    labels:
      - "dependencies"
